
```{r thisOne{{spID}}}

spID <- "{{spID}}"

```

```{r data{{spID}}}

dat_sp <- dat |>
  dplyr::filter(Species == spID)

dat_hab <- dat_sp |>
  dplyr::filter(!is.na(habitat)) |>
  dplyr::count(habitat)

com <- unique(dat$strCommonName[dat$Species == spID])
sp <- unique(dat$strSpeciesName[dat$Species == spID])

text <- paste0(com
               , " were most frequently recorded in habitat(s) "
               , dat_hab |> dplyr::filter(n == max(n)) |> dplyr::pull(habitat) |> envFunc::vec_to_sentence()
               , if(length(unique(dat_hab$n)) > 1) paste0(" although they were also recorded in: "
                                                                       , dat_hab |>
                                                                         dplyr::filter(n != max(n)) |>
                                                                         dplyr::pull(habitat) |>
                                                                         envFunc::vec_to_sentence()
                                                                       )
               )

dat_plot <- dat_summary |>
  dplyr::filter(Species == spID)

text_mod <- if(nrow(dat_plot$data[[1]]) > 3) {

  paste0("There was "
         , if(dat_plot$p > 0.1) "no " else if(dat_plot$p < 0.01) "very good " else if(dat_plot$p < 0.05) "good " else if (dat_plot$p < 0.1) "mild "
         , "statistical support (p = "
         , round(dat_plot$p, 3)
         , ") for the"
         , if(dat_plot$slope > 0) " increasing" else " decreasing"
         , " trend in "
         , com
         )
  
} else {
  
  paste0("There were not enough years with record to estimate a trend in "
         , com
         , " (see plot below)"
         )
  
}


```

### `r com`

There were `r dat_summary$records[dat_summary$Species == spID]` records of `r com` (_`r sp`_). Figure \@ref(fig:map{{spID}}) shows where the records were taken.

`r text` (see figure \@ref(fig:hab{{spID}})).

`r text_mod` (also see figure \@ref(fig:plot{{spID}})).

#### Map

```{r map{{spID}}, fig.cap = paste0("Map of records for ", com)}

m <- dat_sf |>
  dplyr::filter(Species == spID) |>
  dplyr::mutate(year = lubridate::year(Date)
                , year = factor(year)
                ) |>
  tm_shape(bbox = sf::st_bbox(r_poly)) +
  tm_dots(col = "year"
          , palette = "plasma"
          ) +
  tm_shape(r_poly) +
  tm_borders(col = "yellow"
             , alpha = 0.2
             ) +
  tm_scale_bar()

class(m) <- c(class(m), "htmlwidget")

m

```

<br>

#### Habitat

```{r hab{{spID}}, fig.cap = paste0("Habitat types used by ", com)}

dat_hab |>
  dplyr::mutate(habitat = forcats::fct_reorder(habitat, n)) |>
  ggplot(aes(habitat, n)) +
  geom_col(stat = "identity") +
  coord_flip()

```

<br>

#### Plot

```{r plot{{spID}}, fig.cap = paste0("Cells with ", com, " over the years")}

min_year <- min(dat$year, na.rm = TRUE) |> as.character() |> as.numeric()
max_year <- max(dat$year, na.rm = TRUE) |> as.character() |> as.numeric()

ggplot(dat_plot$data[[1]], aes(year, cells)) +
  geom_point() +
  geom_smooth(method = "lm") +
  coord_cartesian(xlim = c(min_year, max_year))

```


